spring:
  application:
    name: parking-service

  config:
    import: "configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/parking_db
    username: root
    password: Sandula#2026$MySQL!
    driver-class-name: com.mysql.cj.jdbc.Driver